name: gcc

on:
  push:

env:
  BUILD_TYPE: Debug
  CC: gcc-14
  CXX: g++-14

jobs:
  installation_test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

      - name: Install
        working-directory: ${{github.workspace}}
        run: sudo cmake --install build

  tests:
    runs-on: ubuntu-24.04
    needs: [installation_test]
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake and install
        working-directory: ${{github.workspace}}
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .
          sudo cmake --install build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

      - name: Build
        working-directory: ${{github.workspace}}/tests
        run: cmake --build build --config ${{env.BUILD_TYPE}} -j2

      - name: Run tests
        working-directory: ${{github.workspace}}/tests/build
        run: ctest